name: Deploy

on:
   push:
      branches:
         - main

jobs:
   build:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout code
         uses: actions/checkout@v2

      - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
            node-version: 18

      - name: Install dependencies
         run: npm ci

      - name: Build project
         run: npm run build

      - name: Deploy to server
         env:
            SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            SERVER: ${{ secrets.SERVER }}
            USERNAME: ${{ secrets.USERNAME }}
         run: |
            cd /var/www/ini-manager.com
            git pull
            npm ci
            npm run build
            pm2 restart all